#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orcamento.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Orcamento")]
	public partial class ModelosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertUsuarioNivel(UsuarioNivel instance);
    partial void UpdateUsuarioNivel(UsuarioNivel instance);
    partial void DeleteUsuarioNivel(UsuarioNivel instance);
    #endregion
		
		public ModelosDataContext() : 
				base(global::Modelos.Properties.Settings.Default.OrcamentoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<UsuarioNivel> UsuarioNivels
		{
			get
			{
				return this.GetTable<UsuarioNivel>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usuarioId;
		
		private string _usuarioNome;
		
		private string _usuarioSenha;
		
		private int _usuarioNivelId;
		
		private int _usuarioAtivo;
		
		private EntityRef<UsuarioNivel> _UsuarioNivel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioIdChanging(int value);
    partial void OnusuarioIdChanged();
    partial void OnusuarioNomeChanging(string value);
    partial void OnusuarioNomeChanged();
    partial void OnusuarioSenhaChanging(string value);
    partial void OnusuarioSenhaChanged();
    partial void OnusuarioNivelIdChanging(int value);
    partial void OnusuarioNivelIdChanged();
    partial void OnusuarioAtivoChanging(int value);
    partial void OnusuarioAtivoChanged();
    #endregion
		
		public Usuario()
		{
			this._UsuarioNivel = default(EntityRef<UsuarioNivel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usuarioId
		{
			get
			{
				return this._usuarioId;
			}
			set
			{
				if ((this._usuarioId != value))
				{
					this.OnusuarioIdChanging(value);
					this.SendPropertyChanging();
					this._usuarioId = value;
					this.SendPropertyChanged("usuarioId");
					this.OnusuarioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioNome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuarioNome
		{
			get
			{
				return this._usuarioNome;
			}
			set
			{
				if ((this._usuarioNome != value))
				{
					this.OnusuarioNomeChanging(value);
					this.SendPropertyChanging();
					this._usuarioNome = value;
					this.SendPropertyChanged("usuarioNome");
					this.OnusuarioNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioSenha", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuarioSenha
		{
			get
			{
				return this._usuarioSenha;
			}
			set
			{
				if ((this._usuarioSenha != value))
				{
					this.OnusuarioSenhaChanging(value);
					this.SendPropertyChanging();
					this._usuarioSenha = value;
					this.SendPropertyChanged("usuarioSenha");
					this.OnusuarioSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioNivelId", DbType="Int NOT NULL")]
		public int usuarioNivelId
		{
			get
			{
				return this._usuarioNivelId;
			}
			set
			{
				if ((this._usuarioNivelId != value))
				{
					if (this._UsuarioNivel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioNivelIdChanging(value);
					this.SendPropertyChanging();
					this._usuarioNivelId = value;
					this.SendPropertyChanged("usuarioNivelId");
					this.OnusuarioNivelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioAtivo", DbType="Int NOT NULL")]
		public int usuarioAtivo
		{
			get
			{
				return this._usuarioAtivo;
			}
			set
			{
				if ((this._usuarioAtivo != value))
				{
					this.OnusuarioAtivoChanging(value);
					this.SendPropertyChanging();
					this._usuarioAtivo = value;
					this.SendPropertyChanged("usuarioAtivo");
					this.OnusuarioAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UsuarioNivel_Usuario", Storage="_UsuarioNivel", ThisKey="usuarioNivelId", OtherKey="usuarioNivelId", IsForeignKey=true)]
		public UsuarioNivel UsuarioNivel
		{
			get
			{
				return this._UsuarioNivel.Entity;
			}
			set
			{
				UsuarioNivel previousValue = this._UsuarioNivel.Entity;
				if (((previousValue != value) 
							|| (this._UsuarioNivel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UsuarioNivel.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._UsuarioNivel.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._usuarioNivelId = value.usuarioNivelId;
					}
					else
					{
						this._usuarioNivelId = default(int);
					}
					this.SendPropertyChanged("UsuarioNivel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioNivel")]
	public partial class UsuarioNivel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usuarioNivelId;
		
		private string _usuarioNivelNome;
		
		private int _usuarioNivelAtivo;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioNivelIdChanging(int value);
    partial void OnusuarioNivelIdChanged();
    partial void OnusuarioNivelNomeChanging(string value);
    partial void OnusuarioNivelNomeChanged();
    partial void OnusuarioNivelAtivoChanging(int value);
    partial void OnusuarioNivelAtivoChanged();
    #endregion
		
		public UsuarioNivel()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioNivelId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usuarioNivelId
		{
			get
			{
				return this._usuarioNivelId;
			}
			set
			{
				if ((this._usuarioNivelId != value))
				{
					this.OnusuarioNivelIdChanging(value);
					this.SendPropertyChanging();
					this._usuarioNivelId = value;
					this.SendPropertyChanged("usuarioNivelId");
					this.OnusuarioNivelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioNivelNome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string usuarioNivelNome
		{
			get
			{
				return this._usuarioNivelNome;
			}
			set
			{
				if ((this._usuarioNivelNome != value))
				{
					this.OnusuarioNivelNomeChanging(value);
					this.SendPropertyChanging();
					this._usuarioNivelNome = value;
					this.SendPropertyChanged("usuarioNivelNome");
					this.OnusuarioNivelNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioNivelAtivo", DbType="Int NOT NULL")]
		public int usuarioNivelAtivo
		{
			get
			{
				return this._usuarioNivelAtivo;
			}
			set
			{
				if ((this._usuarioNivelAtivo != value))
				{
					this.OnusuarioNivelAtivoChanging(value);
					this.SendPropertyChanging();
					this._usuarioNivelAtivo = value;
					this.SendPropertyChanged("usuarioNivelAtivo");
					this.OnusuarioNivelAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UsuarioNivel_Usuario", Storage="_Usuarios", ThisKey="usuarioNivelId", OtherKey="usuarioNivelId")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.UsuarioNivel = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.UsuarioNivel = null;
		}
	}
}
#pragma warning restore 1591
